const emojiList = [
  'angry',
  'anguished',
  'disappointed',
  'disappointed_relieved',
  'dizzy',
  'dizzy_face',
  'do_not_litter',
  'dog',
  'dog2',
  'confounded',
  'confused',
  'heart_eyes',
  'heart_eyes_cat',
  'hushed',
  'joy',
  'kissing',
  'kissing_heart',
  'sob',
  'persevere',
  'stuck_out_tongue',
  'stuck_out_tongue_closed_eyes',
  'stuck_out_tongue_winking_eye',
  'sunglasses',
  'sleepy',
  'sweat',
  'unamused',
  'yum',
  'thumbsup',
];

export default emojiList;
